import './styles.css';
const js =
  import ("rust-wasm");



const main = function(create_sha512) {

  const app = document.createElement('div');
  app.id = 'app';
  const heading = document.createElement('h1');
  heading.innerText = "Sha512 digest generated by WASM (based on Rust's sha2 crate)";
  app.append(heading);

  const outputSection = document.createElement('div');
  outputSection.classList.add('output-section');
  app.appendChild(outputSection);
  const digestLabel = document.createElement('label');
  digestLabel.setAttribute('for', 'digest');
  digestLabel.innerText = 'Digest';
  const digest = document.createElement('output');
  digest.id = 'digest';
  outputSection.appendChild(digestLabel);
  outputSection.appendChild(digest);

  const performanceSection = document.createElement('div');
  performanceSection.classList.add('performance-section');
  app.appendChild(performanceSection);
  const perfLabel = document.createElement('label');
  perfLabel.setAttribute('for', 'perf');
  perfLabel.innerText = 'Duration';
  const perf = document.createElement('output');
  perf.id = 'perf';
  performanceSection.appendChild(perfLabel);
  performanceSection.appendChild(perf);

  const inputSection = document.createElement('div');
  inputSection.classList.add('input-section');
  app.appendChild(inputSection);
  const inputareaLabel = document.createElement('label');
  inputareaLabel.setAttribute('for', 'input');
  inputareaLabel.innerText = 'Input';
  inputSection.appendChild(inputareaLabel);
  const inputarea = document.createElement('textarea');
  inputarea.id = 'input';
  const modifiedHandler = function() {
    let duration = 0;
    const inp = inputarea.value;
    if (inp.length > 0){
      const before = performance.now();
      const sha512sum = create_sha512(inp);
      const after = performance.now();
      digest.innerText = sha512sum;
      duration = after - before;
    } else {
      digest.innerText = '';
    }
    perf.innerText = duration + ' ms';
  };
  inputarea.addEventListener('keyup', modifiedHandler);
  inputarea.addEventListener('paste', modifiedHandler);
  inputSection.appendChild(inputarea);

  document.body.appendChild(app);
}


js.then(js => {
  main(js.create_sha512);
});
